### ISSUE TITLE
React error on index

### ISSUE THREAD

**Issue by latour-gui** [LeGroupeDeFer/infom114_LaboMDL#55]
```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of RefHolder which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node
```

**Comment by findot** [comment]
The problem comes from [React Bootstrap overlay](https://github.com/react-bootstrap/react-bootstrap/issues/3518), not from our code! They don't seem to be willing to fix it so I'd say either we accept the warning or we find another tooltip library.

**Comment by latour-gui** [comment]
ok, I can manage the warning
