### ISSUE TITLE
Create database schema for discussion posts

### ISSUE THREAD

**Issue by dtngan** [LeGroupeDeFer/infom114_LaboMDL#71]
Basic infos:
- post id not null auto inc
- Title optional, null if this is a comment 
- Author not null
- Date time not null
- Parent = post id if this is a comment, null otherwise
- Tag

Vote:
- Post id not null
- Author not null
- Date time not null
- Value = +1 or -1

It's not necessary to create a table for the comments because their fields are almost as same as posts, unless they point to a post original as root.

Need a view that retrieves all informations related to a post id, including comments and votes

**Comment by dtngan** [comment]
Tags will be stored in a different table.

Ref: https://stackoverflow.com/questions/3508207/best-practice-for-storing-tags-in-a-database

**Comment by latour-gui** [comment]
Hey what's the `nb_votes` value ?

Also, is it ok if I add a `deleted_at` field to implement soft-delete ?
