### ISSUE TITLE
fix test `posts::actions::upvote_and_remove_vote`

### ISSUE THREAD

**Issue by latour-gui** [LeGroupeDeFer/infom114_LaboMDL#87]
Hey @findot 

I feel like the rank calculation after the cancellation of a vote is messed up somewhere.

Please refer to this screenshot to find the issue
![image](https://user-images.githubusercontent.com/56428897/80968786-d7da7900-8e18-11ea-8db9-645ff03704ca.png)

Ty

**Comment by findot** [comment]
fixed in #66
